### ISSUE TITLE
Invalid Web IDL: Sanitizer.config attribute type cannot be dictionary

### ISSUE THREAD

**Issue by tidoust** [WICG/sanitizer-api#107]
A recent commit [switched config to be an attribute getter](https://github.com/WICG/sanitizer-api/commit/f3f52ce95d9516f525c071a7f9f56c21205840be). However, that is [forbidden in Web IDL](https://heycam.github.io/webidl/#idl-attributes): "the type of the attribute [...] must not be a nullable or non-nullable version of [...] a dictionary type".

(I suspect one reason for the rule is that devs expect attributes to return the same object, as in `obj.config === obj.config`, and that cannot easily be enforced when a readonly attribute returns a dictionary)

**Comment by otherdaniel** [comment]
Right. This was the reason for [originally doing it as methods](https://github.com/WICG/sanitizer-api/pull/80/files#r616408446). However, we've repeatedly been told that this is bad API ergonomics, and that developers would expect to use attribute syntax (`s.config` instead of `s.config()`).

At this point, I'm rather confused whether I'm using the syntax wrong -- that is, we can get our attribute syntax for `.config`, but not with an actual attribute -- or whether we're just caught between two different expectations (accessor syntax vs. object identity for accessor values) and get to pick which one we violate.

Can I return a dictionary copy and get accessor syntax in WebIDL? How?

**Comment by dontcallmedom** [comment]
a couple of non-fully-formed thoughts:
 - `getConfiguration()` as a method name would probably avoid some of the pushback on `config()` and has precedents in [`MediaKeySystemAcces`](https://dontcallmedom.github.io/webidlpedia/names/MediaKeySystemAccess.html) and [`RTCPeerConnection`](https://dontcallmedom.github.io/webidlpedia/names/RTCPeerConnection.html)
 - there is a related [WebIDL discussion](https://github.com/heycam/webidl/issues/981) which (indirectly) itself points to [ReadOnlyArray](https://github.com/heycam/webidl/issues/796) as a possible solution, possibly already achievable through [ObservableArray](https://heycam.github.io/webidl/#idl-observable-array)?

Paging @leaverou since this relates to the [feedback she conveyed on the spec](https://github.com/WICG/sanitizer-api/pull/80/files#r616408446).

**Comment by tidoust** [comment]
Related TAG design principle: [Attributes should behave like data properties](https://w3ctag.github.io/design-principles/#attributes-like-data) which says "Ensure that obj.attribute === obj.attribute is always true. Don’t create a new value each time the getter is called".

**Comment by LeaVerou** [comment]
> Related TAG design principle: [Attributes should behave like data properties](https://w3ctag.github.io/design-principles/#attributes-like-data) which says "Ensure that obj.attribute === obj.attribute is always true. Don’t create a new value each time the getter is called".

Does `.config` create a new value every time the getter is called?

**Comment by otherdaniel** [comment]
> > Related TAG design principle: [Attributes should behave like data properties](https://w3ctag.github.io/design-principles/#attributes-like-data) which says "Ensure that obj.attribute === obj.attribute is always true. Don’t create a new value each time the getter is called".
> 
> Does `.config` create a new value every time the getter is called?

I don't think WebIDL has an opinion on that, since WebIDL is convinced this doen't exist.

The 'naive' implementation (at least in Chromium) would indeed create a new value each time, but that could also be implemented differently by memo-izing the value once and then returning the same value each time

**Comment by dontcallmedom** [comment]
re memoizing, https://github.com/heycam/webidl/issues/981#issuecomment-839939584 alludes to a would-be `[Cached]` extended attribute (but also note the concern re mutability)

**Comment by otherdaniel** [comment]
> re memoizing, [heycam/webidl#981 (comment)](https://github.com/heycam/webidl/issues/981#issuecomment-839939584) alludes to a would-be `[Cached]` extended attribute (but also note the concern re mutability)

Oh, right. If we were to return the same dictionary, then that dictionary could be modified by a first caller, and the second caller would then see the same, modified dictionary. That's just a bad idea. So after a second thought, I'm going to say that `.config` would indeed create a new value every time. Which would disregard the `s.config === s.config` expectation.

**Comment by LeaVerou** [comment]
I think it's fine to create a new object when the configuration actually changes, the spirit of the TAG guidance is that you should return the same object if the value hasn't changed.

**Comment by otherdaniel** [comment]
Well, Sanitizers don't change configurations anyways; configuration is a constructor thing. The point is that JavaScript doesn't have constant objects. I.e.:

```js
const s = new Sanitizer( ...bla bla...);
let c1 = s.config():
let c2 = s.config();
c1.hello = "world";  // Modify the dictionary we received.
"world" == c2.hello;  // true., c1 & c2 are the same object, and thus c2 "sees" the modification of c1
```

That could be very extra suprising if some part of the code modifies the return value - for example, to build a new configuration - and then another part of the code tries to examine it. Example:

```js
const main_sanitizer = new Sanitizer(...);  // A carefully configured sanitizer for our application.

// Somewhere in libary we want to be slightly more strict.
// Intent: Build a new sanitizer based on main_sanitizer.
// Reality: Have modified main_sanitizer's config.
let config = main_sanitizer.config;
config.blockElements.push("table", "td", "th", "tr");  // We hate tables.
const my_sanitizer = new Sanitizer(config);

// Somewhere else entirely:
let my_config = main_sanitizer.config.  // Oops. Now we're really seeing my_sanitizer's config.
```

**Comment by Sora2455** [comment]
JavaScript has frozen objects, but I don't think that resolves the problem here because freezing an array won't stop someone calling push etc on it.

**Comment by LeaVerou** [comment]
@Sora2455 Yes, it will. You can try it out yourself:

```
> let a = Object.freeze([1, 2, 3]); a.push(4)
VM188:1 Uncaught TypeError: Cannot add property 3, object is not extensible
    at Array.push (<anonymous>)
    at <anonymous>:1:3
```

**Comment by otherdaniel** [comment]
Thanks for bringin up 'freeze'. Frozen is apparently shallow, so Lea's example will no longer work if it's an array as a dictionary value. But I guess we could freeze recursively.

Is there precedent for relying on 'frozen' return values in JS APIs?

**Comment by LeaVerou** [comment]
> Thanks for bringin up 'freeze'. Frozen is apparently shallow, so Lea's example will no longer work if it's an array as a dictionary value. But I guess we could freeze recursively.
> 
> Is there precedent for relying on 'frozen' return values in JS APIs?

I can't think of anything for objects, but there's a lot of precedent with lists of values. Here's [the long ongoing related discussion](https://github.com/w3ctag/design-principles/issues/50).

**Comment by domenic** [comment]
I'd strongly recommend using a method. There's no precedent for deeply frozen objects in JavaScript or web APIs (which is why the pattern is prohibited by Web IDL).

**Comment by domenic** [comment]
The other usual alternative is flattening the properties, e.g. instead of using `sanitizer.config.allowElements` using `sanitizer.allowElements` or `sanitizer.configAllowElements`. That looks a bit less suitable here though.

**Comment by otherdaniel** [comment]
Hmm. So far, I'm not seeing a viable solution, or even consensus on a general direction. I'll revert PR #104 and close out this issue.

Thanks all for the discussion, and please do feel free to re-open this if there's additional info or a good proposal on how to solve this.

**Comment by dontcallmedom** [comment]
when reverting #104, I would suggest again that `getConfiguration()` would be better than `config()`

**Comment by otherdaniel** [comment]
Reverted. Also renamed the methods to `.getConfiguration()` / `.getDefaultConfiguration()`.

**Comment by LeaVerou** [comment]
Coming here late, but +1 for using a function, I think that is the least surprising option.
(to clarify, I wasn't suggesting deeply frozen objects at any point, just answering related questions)
