### ISSUE TITLE
sanitizeFor('script', ...) and scriptEl.setHTML()

### ISSUE THREAD

**Issue by mozfreddyb** [WICG/sanitizer-api#125]
I have observed a surprise when implementing & testing, whic his as follows:
- `mySanitizer.sanitizeFor('script', ...)` returns null
- `scriptEl.setHTML(...)` throws.

I believe that sanitizeFor should also throw, shouldn't it? 

Tagging @otherdaniel who I believe wrote the test.

**Comment by otherdaniel** [comment]
Agree on observation. Not sure on conclusion. That said, this is really about API usability, and your opinion is as good as mine.

-----

What I was thinking:

- The contract for `.sanitizeFor` is to return a safe version of the thing that's passed in, and if there's no safe version then it will return just that: Nothing.
- The contract for `.setHTML` is to modify the DOM with a safe version of the thing that's passed in, and if there's no safe version then... there is no way to fullfil the contract, because: How would it modify the tree? That's why it throws and thereby forces the callee into an error-handling control flow.

The difference - in my intuition - is that the "natural" error handling for "return something" is to return nothing; while "modify something" doesn't (generally) have "natural" error handling.

(Arguably, `setHTML` with invalid parameters could also just delete the children of the current element. That is: we could imagine `.setHTML` as a combo operation of `.replaceChildren( ...sanitize...)`and let it regress to `.replaceChildren()` if `sanitize` cannot complete.)

I still think this logic makes sense, but we could certainly do it differently.

**Comment by mozfreddyb** [comment]
It seems that there's no "idiomatic" solution in the HTML/JS/DOM space, so we're open to suggestions. @otherdaniel and I agreed to collect more feedback before resolving this.
