### ISSUE TITLE
Should all non-HTML elements be unknown?

### ISSUE THREAD

**Issue by evilpie** [WICG/sanitizer-api#167]
https://wicg.github.io/sanitizer-api/#element-kind says "`unknown`, if element is not in the HTML namespace". Is that really intentional?

**Comment by evilpie** [comment]
Many of the WPT tests like [sanitizer-names.https.tentative.html](https://searchfox.org/mozilla-central/source/testing/web-platform/tests/sanitizer-api/sanitizer-names.https.tentative.html) seem to not expect this behavior. Otherwise they would have to combine `allowUnknownMarkup: true` with e.g. `allowElements: ["svg:svg"]`. @otherdaniel

**Comment by otherdaniel** [comment]
No, not intentional, and the namespace bits in the spec should be re-written (or at least broadly edited). The intent is that `unknown` should be all the stuff that the browser doesn't know what to do with, but it certainly knows what to do with MathML and SVG elements.

I tried to separate the WPT tests into tentative and not-tentative cases - note that there's a [sanitizer-names.https.html](https://searchfox.org/mozilla-central/source/testing/web-platform/tests/sanitizer-api/sanitizer-names.https.tentative.html) and a [sanitizer-names.https.tentative.html](https://searchfox.org/mozilla-central/source/testing/web-platform/tests/sanitizer-api/sanitizer-names.https.html) - with the goal of separating out the test cases that are (hopefully) settled (non-tentative), and the others.

Our current implementation doesn't support namespaced content (which is still behind a flag, to wait for better spec support & cross-browser agreement), and in the context of an HTML-only sanitizer the spec statement should work okay. We should still fix the spec, though. The thing we're shipping should pass all the non-tentative test cases.

**Comment by evilpie** [comment]
I tried to prototype this in Gecko, because we already have lists of known [MathML](https://searchfox.org/mozilla-central/rev/8dd35cd8f5284fbaa506aab02fe42fc87efb249e/dom/base/nsTreeSanitizer.cpp#649) and [SVG](https://searchfox.org/mozilla-central/rev/8dd35cd8f5284fbaa506aab02fe42fc87efb249e/dom/base/nsTreeSanitizer.cpp#324) elements. 

However if we start returning `regular` from _**element kind**_ we also have to change the [sanitize action for an element](https://wicg.github.io/sanitizer-api/#sanitize-action-for-an-element), because that will always use the baseline element allow list, which doesn't include MatML/SVG elements.

**Comment by fred-wang** [comment]
Hi, I would suggest that the default list of allowed elements from the MathML namespace are taken from MathML Core: https://w3c.github.io/mathml-core/#mathml-elements-and-attributes

A bit tangential, but I guess there are more to discuss like e.g. what are the allowed attributes on non-HTML elements. For MathML, I'd suggest again to follow MathML Core. Maybe relevant for implementation only but note that MathML elements accept many HTML attributes such as `on*` event handler: https://w3c.github.io/mathml-core/#global-attributes

**Comment by annevk** [comment]
Let's fold this into #103 as this is mainly about getting lists of SVG and MathML elements.
