### ISSUE TITLE
Streaming support

### ISSUE THREAD

**Issue by zcorpan** [WICG/sanitizer-api#190]
See https://github.com/whatwg/html/issues/8759#issuecomment-1462414347

The HTML parser spec is streaming (although the tree is sometimes mutated in interesting ways). In https://github.com/whatwg/html/issues/2142 there's a proposal to add a streaming API for the parser.

If the sanitizer API should be usable with the streaming HTML parser API, then sanitization needs to also be streamable.

It seems possible to perform sanitization in the tree builder stage of the HTML parser: https://html.spec.whatwg.org/multipage/parsing.html#creating-and-inserting-nodes

**Comment by annevk** [comment]
Since parsing and sanitizing are tightly coupled in the current APIs this is no longer a concern.

**Comment by annevk** [comment]
There's renewed interest in streaming parsing APIs so we should probably keep this open for v2.

**Comment by otherdaniel** [comment]
> There's renewed interest in streaming parsing APIs so we should probably keep this open for v2.

This was briefly discussed in yesterday's meeting. Generally, this looks good to me. Some initial opinions, without having thought this through:

* The present Sanitizer design is very HTML-parser-adjacent. It should be easy to apply it to whatever the HTML parser produces, in whatever granularity.
* Sanitizer looks at one node at a time; Elements and its attributes are considered together. There are no decisions that take several nodes into account. That should make it easy to apply Sanitizer to sub-trees or partial trees.
* The replaceWithChildren action does need to know its children. The decision is node-local, but the action itself requires that the node 'knows' its children. The 'driver loop' wants to know about templates and shadow hosts in order to recurse into them. This would likely need to be taken into account.
* The API was a bit unclear to me; but I'll guess if there's an option bag somewhere it could contain a SanitizerConfig. I wonder if it'd make sense to have safe/unsafe variants.

**Comment by zcorpan** [comment]
> * The API was a bit unclear to me; but I'll guess if there's an option bag somewhere it could contain a SanitizerConfig. I wonder if it'd make sense to have safe/unsafe variants.

See https://github.com/WICG/declarative-partial-updates/issues/42

**Comment by noamr** [comment]
> > There's renewed interest in streaming parsing APIs so we should probably keep this open for v2.
> 
> This was briefly discussed in yesterday's meeting. 

That's great! I wasn't expecting this feature to be discussed *before* it was re-opened. Seems like you've achieved time travel.

> Generally, this looks good to me. Some initial opinions, without having thought this through:
> 
> * The replaceWithChildren action does need to know its children. The decision is node-local, but the action itself requires that the node 'knows' its children. The 'driver loop' wants to know about templates and shadow hosts in order to recurse into them. This would likely need to be taken into account.

Yea, the streaming would have to be buffered until the element is closed.

> * The API was a bit unclear to me; but I'll guess if there's an option bag somewhere it could contain a SanitizerConfig. I wonder if it'd make sense to have safe/unsafe variants.

This would either be an extension to `setHTML` or a similar variant with a different name.

I guess we wouldn't need a new API for the sanitizer itself, as it's just a builder of a policy, and we would only need new API for `TrustedTypes`. I think I understand [this comment](https://github.com/WICG/sanitizer-api/issues/190#issuecomment-1768243791) better now.

**Comment by zcorpan** [comment]
Some interesting cases to think about are

- foster parenting, what should happen if you do `replaceWithChildrenElements: ['table']` and the input is `<table><tr><td>1</td></tr>foo</table>`? Should the "foo" be inserted into the inert document fragment, or before the `tbody` element (which doesn't have a parent `table` element)? Or should this disable foster parenting altogether? Should we also yank the other table-related elements?
- AAA can create two elements from one start tag (and reparent during parsing), e.g. `<a>1<p>2</a>` ([demo](https://software.hixie.ch/utilities/js/live-dom-viewer/saved/14242))
- reconstructing formatting elements can also create multiple elements from one start tag, e.g. `<div><a></div><p>x<p>x` ([demo](https://software.hixie.ch/utilities/js/live-dom-viewer/saved/14243))

**Comment by mozfreddyb** [comment]
Another conrer case that has bypassed sanitizers in the past is the maximum nesting depth of 512 elements.
When fragment parsing, you start at 0 and not the nesting depth of the current element, but it still matters:
After receiving an element at the depth of 512, all new elements are created as siblings, rather than children.
This means, that when receiving a stream of elements, the parserneeds to stop updating the "context element pointer" and leave it at the shared parent of the sibling elements.

**Comment by foolip** [comment]
In addition to enforcing sanitizer decisions when [inserting](https://html.spec.whatwg.org/#insert-a-foreign-element) elements, we also need to look at code paths that append directly and don't go through the insertion location adjustment machinery.

Looking at [create an element for a token](https://html.spec.whatwg.org/multipage/parsing.html#create-an-element-for-the-token) call sites, here's what I found:
- The ["before html" insertion mode](https://html.spec.whatwg.org/#the-before-html-insertion-mode) creates and appends an `<html>` element to the document.
- The ["in head" insertion mode](https://html.spec.whatwg.org/#parsing-main-inhead) has a bunch of special handling of `<script>` elements that inserts without reference to an algorithm at step 6.
- The [adoption agency algorithm](https://html.spec.whatwg.org/#adoption-agency-algorithm) creates and appends nodes.
- [Parsing XML documents](https://html.spec.whatwg.org/#parsing-xhtml-documents), not sure if sanitizer can apply to XML parsing?
