### ISSUE TITLE
prototype API

### ISSUE THREAD

**Issue by mozfreddyb** [WICG/sanitizer-api#22]
For the sake of prototyping, I would like to suggest an API that looks like this (but obviously subject to change):

* You construct a Sanitizer object by supplying options (or accepting the default): `new Sanitizer(options)`
* The sanitizer object has various functions depending on the return type required:
** `sanitize()` returning a DocumentFragment
** `sanitizeToString()` returning a DOMString
* All of those functions should accept documentfragments, documents, strings

WebIDL, scrambled together and likely not entirely correct:

```webidl
typedef (DOMString or DocumentFragment or Document) SanitizerInput;

[Exposed=Window]
interface Sanitizer {
  constructor(optional SanitizerOptions options); // optionality still discussed below
  DocumentFragment sanitize(optional SanitizerInput input);
  DOMString sanitizeToString(optional SanitizerInput input);
};

// unimplemented during prototyping
interface SanitizerOptions {}
```

**Comment by otherdaniel** [comment]
+1

Two rather minor nitpicks:

1, optionality: I'd have done it the other way round.
  - constructor argument: What would that even do? If we're trying to avoid implicit behaviour (see #19), we  can hint in the API that the developer must supply the rules by making it non-optional.
  - sanitize* methods: Making their arguments optional allows the caller to dispense with a null-check (or stringify-able check), so that people can just blindly dump stuff into the sanitizer and be sure to have some resonable output. (Possibly an empty string.)

2, I think web idl mostly uses capitalized names for types (SanitizerOptions, SanitizerInput)

**Comment by mozfreddyb** [comment]
>     * constructor argument: What would that even do? If we're trying to avoid implicit behaviour (see #19), we  can hint in the API that the developer must supply the rules by making it non-optional.

I'm not sure I fully get the ergonomics. Do we expect authors to always spell out the exact set of elements they want to allow? I want us to offer a safe-default that will be (hopefully) adopted by the majority.
I suppose we could set a regularly-re-defined constant `Sanitizer.NO_XSS` that is slightly different per user-agent (e.g., due to element/attribute/event-handler), which would make it both forward-compatble and explicit?
Would that work for you?

> 
>     * sanitize* methods: Making their arguments optional allows the caller to dispense with a null-check (or stringify-able check), so that people can just blindly dump stuff into the sanitizer and be sure to have some resonable output. (Possibly an empty string.)
> 
good point. I'll edit in my initial comment

> 
> 2, I think web idl mostly uses capitalized names for types (SanitizerOptions, SanitizerInput)
same as above. I'll edit.

**Comment by otherdaniel** [comment]
> I suppose we could set a regularly-re-defined constant Sanitizer.NO_XSS that is slightly different per user-agent (e.g., due to element/attribute/event-handler), which would make it both forward-compatble and explicit?
Would that work for you?

Yes.

I'm assuming that there can't really be a single default, and that in the end there'll be a small handful of common use cases, and that it should be easy to for devs to use one (or several) of them. Maybe something like: no script (NO_XSS), no script & no style definitions (but style references), only simple markup (bold, italics). All of them should be (and can be) safe.

I'm guessing the no-XSS one would be adapted if the browser grows more ways to execute script; but e.g. the only-simple-markup one would be easy to keep unchanged.

I'd image the end result to look something like so:
```
const a = new Sanitzer(NO_XSS);
const b = new Sanitzer(SIMPLE_MARKUP);
const c = new Sanitizer(Object.assign(SIMPLE_MARKUP), {'extra_allowed': ['div', 'strike', 'myfancyelem']}));

a.sanitize(....);  // Blocks everything the browser will understand to be script.
b.sanitize(....);  // Allows only <b>, <i>
c.sanitize(...);  // Allows a bit more than b.sanitize.

```

(I'm not sure what the correct categories are, and how many, etc., but the general structure would make sense to me.)

**Comment by mozfreddyb** [comment]
I noticed my proposed prototype WebIDL at the top has input as optional (so unsupplied arguments wouldn't throw). My mistake was that I conflated the various cases for supplying "empty" content and how that would fail. Here's a summary of what I understand _should_ be the case (and the WebIDL needs to be updated for it!).


sanitizeToString("") -> returns empty string
sanitizeToString() -> throws, missing argument
sanitizeToString(undefined) -> parses through the Fragment Parsing algorithm as "undefined"

Firefox does not show this behavioryet , [which I'm going to fix](https://bugzilla.mozilla.org/show_bug.cgi?id=1664485). Currently, all of those cases return the empty string.). This will fix most existing mismatches with tests we already have in WPT.

Remaining issues (will be filed against WPT repo):
- interface should be only exposed to SecureContexts
- interface should include `sanitize` function

**Comment by otherdaniel** [comment]
> sanitizeToString(undefined) -> parses through the Fragment Parsing algorithm as "undefined"

Hm. How would WebIDL "know" that undefined is a DocumentFragment, rather than a Document?

On our side, we currently have only implemented String->String and String->DocumentFragment, and IIRC our definition of what happens with null or undefined are largely a fallout from whatever our IDL compiler does with that. And the tests reflect this, too. It might well be that the tested-for-behaviour isn't all that sensible.

Re-reading https://heycam.github.io/webidl/#es-union:
- IIUC, null and undefined are handled in clauses 1. + 3., and are in both cases handled identically.
- In the current/planned definition, none of the SanitizerInput types are nullable. Thus, neither 1. nor 3. applies.
- Clause 12 handles [conversion to string](https://tc39.es/ecma262/#sec-tostring), which converts null and undefined to their string representations.

So.. I'm guessing the tests are currently wrong?
Should we make SanitizerInput nullable? (I don't have any strong argument here, neither for nor against.)

**Comment by mozfreddyb** [comment]
fwiw, I'd rather have the methods return something than author code failing due to uncaught exceptions.
Our existing prototype has `optional SanitizerInput`.

**Comment by koto** [comment]
> fwiw, I'd rather have the methods return something than author code failing due to uncaught exceptions.
> Our existing prototype has `optional SanitizerInput`.

Why? You're calling a sanitizer on an input, failing to provide one is an error. Similarly, `Node.appendChild()` expects a Node argument and throws a TypeError. Input validation of the arguments is pretty common for web APIs, that's why we have WebIDL layer.

**Comment by mozfreddyb** [comment]
Hmm, coming back to this, you're right. It shouldn't be optional.

**Comment by otherdaniel** [comment]
Done. Current spec follows this proposal.
