### ISSUE TITLE
Broken image in explainer.md

### ISSUE THREAD

**Issue by 22jcampb** [WICG/sanitizer-api#230]
The image in line 1 (Build Status link) is broken, it displays the "broken image" logo and a text link saying "build status".
[explainer.md](https://github.com/WICG/sanitizer-api/blob/main/explainer.md)

**Comment by otherdaniel** [comment]
Reporter is correct. Same at the bottom of the main page.

The links go to Travis CI, which we apparently stopped using a while ago in favour of GitHub's built-in actions. Those already have a "Deployments" widget in the right column of the main page. So I suggest we just remove the CI links, since the info is already available from the project's main page.
