### ISSUE TITLE
toString is reserved identifier.

### ISSUE THREAD

**Issue by otherdaniel** [WICG/sanitizer-api#30]
[toString](https://wicg.github.io/sanitizer-api/#sanitizer-api) is a [reserved identifier in WebIDL](https://heycam.github.io/webidl/#idl-names). (See sentence starting with "The identifier of any".) We need to pick a different name.

**Comment by otherdaniel** [comment]
Candidates:
- saneFromString / saneFromFragment
- sanitze / sanitizeToFragment
- stringFrom / fragmentFrom   (Since this is called on a sanitizer instance, the reader already has the context that this is about sanitzing)

**Comment by shhnjk** [comment]
I like sanitze 😊 I always feel bad about assigning string to innerHTML after working on Trusted Types, so something that is different from word _string_ would be nice 😊

**Comment by shhnjk** [comment]
Can people vote if you all prefer _sanitizeToString_ or _sanitizeToHTML_?
If you like _sanitizeToHTML_ please add a 👍 reaction in this comment. If you like _sanitizeToString_, then add a 👎 reaction in this comment.
If you hate both, add a comment 😊

CC: @koto, @mikewest, @cure53

**Comment by koto** [comment]
This depends on https://github.com/WICG/sanitizer-api/issues/20#issuecomment-677797865. If TT would allow creating a `DocumentFragment` for a given sanitizer config, there ideally should be a way to return a `TrustedHTML` instance from said config too. 

I don't think we should even be offering strings as a return value for HTML in new APIs. We know what that led to.

**Comment by shhnjk** [comment]
> This depends on [#20 (comment)](https://github.com/WICG/sanitizer-api/issues/20#issuecomment-677797865). If TT would allow creating a `DocumentFragment` for a given sanitizer config, there ideally should be a way to return a `TrustedHTML` instance from said config too.

Agreed 😊
> I don't think we should even be offering strings as a return value for HTML in new APIs. We know what that led to.

I'm against this idea for Sanitizer API (though this might make sense for other APIs)🙁 The reason being, because we need to be flexible about whatever people decides to add in their _SanitizerConfig_, we do need to return string when we are unsure if the output would cause an XSS. This will ensure that the output is string, and therefore it's still unsafe to assign it as an HTML.

However I have to agree that this would make a confusion that _sanitizeToHTML_ might return a string, which is weird 😂
Maybe indeed we have to create 2 different methods, one with arbitrary config called _sanitizeToString_, and one with only default config or stricter called _sanitizeToHTML_. And calling _sanitizeToHTML_ with weak _SanitizerConfig_ would just return _emptyHTML_.

**Comment by koto** [comment]
Agreed. I guess a right way to put it, there should ideally be 3 distinct methods - for fragment, a string, and `TrustedHTML`. These methods might throw - for example, if a conversion to fragments or `TrustedHTML` from a given sanitizer instance was violating TT restrictions on a page, but I imagine there might be other reasons for throwing too.

**Comment by otherdaniel** [comment]
Marking as closed, since there's no more `toString` left in the current spec draft. Jun's/Koto's requests for TT methods is best handled with #31
