### ISSUE TITLE
What should be in the default list?

### ISSUE THREAD

**Issue by iVanlIsh** [WICG/sanitizer-api#38]
Here are the parts I thought of:
__default dropElements:__ "SCRIPT", "ANNOTATION-XML", "AUDIO", "COLGROUP", "DESC", "FOREIGNOBJECT", "HEAD",      "IFRAME", "MATH", "MI", "MN", "MO", "MS", "MTEXT", "NOEMBED", "NOFRAMES", "PLAINTEXT", "STYLE", "SVG",       "TEMPLATE",  "THEAD", "TITLE", "VIDEO", "XMP" (copied from [FORBID_CONTENTS](https://github.com/cure53/DOMPurify/blob/b552659b914a3849f5eb94b4aa6f4cfe9962bdc3/src/purify.js#L251))
__default blockElements:__ 
__default dropAttributes:__ "on*", "src": ["EMBED"], "codeBase": ["OBJECT"], "data": ["OBJECT"] (partially from [Trusted Types list](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/trustedtypes/trusted_type_policy_factory.cc;drc=46ca9af65708fb0c81c3f236c88efaa822d5d389;l=151))

Any opinions on this? @otherdaniel @koto @shhnjk @mozfreddyb

**Comment by otherdaniel** [comment]
In addition to [DOMPurify](https://github.com/cure53/DOMPurify/blob/b552659b914a3849f5eb94b4aa6f4cfe9962bdc3/src/purify.js#L25) and Chomium's [TrustedTypes](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/trustedtypes/trusted_type_policy_factory.cc;l=150-163), there is also:

- Firefox, specifically [nsTreeSanitizer](https://searchfox.org/mozilla-central/source/dom/base/nsTreeSanitizer.cpp), and very specifically [nsTreeSanitizer::MustPrune](https://searchfox.org/mozilla-central/source/dom/base/nsTreeSanitizer.cpp#1026)
- Chromium (again), with the [ParserContentPolicy](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/dom/parser_content_policy.h;l=32?q=ParserContentPolicy&ss=chromium%2Fchromium%2Fsrc), and specifically [ScriptingContentIsAllowed](https://source.chromium.org/search?q=ScriptingContentIsAllowed&ss=chromium%2Fchromium%2Fsrc)


These don't seem to agree on much beyond the `<script>` tag, so I suspect this will be a bit of a research project. :)

**Comment by otherdaniel** [comment]
Another sanitizer that's in active use, [Closure Sanitizer](https://github.com/google/closure-library/tree/master/closure/goog/html/sanitizer), specifically [block list](https://github.com/google/closure-library/blob/master/closure/goog/html/sanitizer/tagblacklist.js), [allow list](https://github.com/google/closure-library/blob/master/closure/goog/html/sanitizer/tagwhitelist.js), and [attributes](https://github.com/google/closure-library/blob/master/closure/goog/html/sanitizer/attributewhitelist.js).

**Comment by mozfreddyb** [comment]
Let's collect a matrix on a spreadsheet to gather allow-lists of
- elements
- attributes
- elements whose content must be removed with them
for a variety of projects.

I think we could start with DOMPurify, Chromium and Firefox implementation in a spreadsheet, 
(If someone wishes to contribute lists for others, e.g. closure sanitizer, [bleach](https://github.com/mozilla/bleach),[ammonia](https://github.com/rust-ammonia/ammonia/issues/), I wouldn't be opposed :))

**Comment by mozfreddyb** [comment]
[I started collecting things in a spreadsheet](https://docs.google.com/spreadsheets/d/1iszyGalKrceVeUnM40hCbiY8VIp2v8D5bNnIVb_agxQ/edit?usp=sharing). Starting simple with just HTML elements, but happy to give access and grow incrementally.

**Comment by mozfreddyb** [comment]
I've started aligning the gecko sanitizer with others, in terms of default allowed elements. Assuming #58 passes as acceptable, I'd suggest we make this the list of default allowed HTML elements:

`
a, abbr, acronym, address, area, article, aside, audio, b, bdi, bdo, big, blockquote, body, br, button, canvas, caption, center, cite, code, col, colgroup, datalist, dd, del, details, dfn, dir, div, dl, dt, em, fieldset, figcaption, figure, font, footer, form, h1, h2, h3, h4, h5, h6, head, header, hgroup, hr, html, i, img, input, ins, kbd, keygen, label, legend, li, link, listing, map, mark, menu, meta, meter, nav, nobr, noscript, ol, optgroup, option, output, p, pre, progress, q, rb, rp, rt, rtc, ruby, s, samp, section, select, small, source, span, strike, strong, sub, summary, sup, style, table, tbody, td, textarea, tfoot, th, thead, time, tr, track, tt, u, ul, var, video, wbr`

**Comment by otherdaniel** [comment]
What about:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/portal
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot  (Not sure, really.)


More importantly: The way I've currently formalized the spec the defaults cannot be overriden, based on previous discussion. With a default-allow-list, rather than a default-block-list, it would therefore be impossible to ever add elements - like custom elements - to the Sanitizer. Is this the intention?

(The same problem arises for non-HTML-defined attributes, which I think are common for use with some libraries.)

More specifically:
- If I want my Sanitizer to pass through `<bla>` or `<custom-bla>`, should that be configurable?
- If so, I suspect `<script>` very much shouldn't be configurable in any case. How can I formalize this to cover for this difference?

**Comment by mozfreddyb** [comment]
Again, I think custom elements need a separate config that's aside from the elements that are part of the HTML spec, along the lines of "valid custom elements names" in #53.

Adding others, I suppose will be part of our next call, hm? I was hoping we could settle with "never allow something to be added"

- dialog: I meant to add that, sorry.
- picture: Same, oops
- portal: Firefox doesn't support portal. We might have to accept ambiguities like that?
- slot: Firefox supports it. I never heard of it. Seems harmless. Let's add.

**Comment by otherdaniel** [comment]
Elsewhere I whined a bit about default handling and how to formalize it for the spec. This is arguably somewhat tangential for this exact issue, but this is what triggered the current discussion. My plan/proposal would be this:

1. We distinguish between built-in and defaults. The built-ins are eternally non-overriable. The defaults are what you get when you don't supply your own config. This would allow us to be much more aggressive in the defaults, without giving up on the never-XSS property of Sanitizer.
   (E.g., we could also default-disallow deprecated but harmless elements.)
2. Freddy's list becomes the default, presumably alongside a similar list for attributes.
3. The built-ins become a block-list that's sppecifically targeted on script execution.

Also:
1. We'll introduce another boolean config item for non-browser-defined elements, similar to custom elements. That's 1, convenient to use, and 2, turns allow-vs-block into a simple set operation (vs the set of browser-defined elements).
2. Yifan correctly pointed out that we currently have two behaviours for blocking (removing the element with children, and removing the element bug keeping the children). It'd make sense to have both behaviours for allowing to.

Formalization:
- New bool setting for non-browser defined elments. (Default off.) I guess antoher one for attributes.
- builtin block lists. Anything they block is final.
- builtin defaults for the allow list (for elements and attributes), as discussed above. A config with its own allow list would override the default.

**Comment by shhnjk** [comment]
> The built-ins become a block-list that's sppecifically targeted on script execution.

I mentioned this elsewhere, but I don't like the idea of deny-list in the Sanitizer.
For example, let's imagine that the `<portal>` has the same behavior as `<iframe>`, and assigning JavaScript URL to `src` attribute will result in an XSS in the parent document.

In the deny-list case, we have to move quickly in both someone noticing that this has to be added to the deny-list as well as have consensus in the spec to add that. Which means the Sanitizer API will **block** the feature release of `<portal>` tag.

Where as in allow-list case, we aren't allowing the new tag/attribute (because it's not in the allow-list), so we can have as much time as we want for discussion to add a new tag/attribute in to the spec.

And when an existing safe tag/attribute becomes dangerous (e.g. [Declarative Shadow DOM](https://twitter.com/cure53berlin/status/1318818166303281153)), both deny-list and allow-list approach has to be updated, so that's same amount of speed on both approach.

**Comment by otherdaniel** [comment]
PR #60 is my attempt at formalizing this, along what I said earlier. The first commit is my version from the previous comment; the second commit picks up Jun's request to use allow lists for the built-ins.

The second version is surprisingly awkware, since in order to avoid the problem of not overblocking in the non-overridable config, the rule needs to make exceptions for both custom and unknown elements. Additionally, it's surprisingly hard to see what the difference between built-in and default is.

Any comments? Is this moving in the right direction?

**Comment by shhnjk** [comment]
I think the idea of `eternally non-overridable` is probably impossible (unless we only want to support few tags in built-ins :P). As the Web evolves, new tags/attributes will be introduced, and that will suddenly make deny-list built-ins insecure. So we have to accept that either we take deny-list or allow-list approach in built-ins, we would have to change it over time. 

However, I think allow-list will reduce the breakage of web apps in the long term, as we will mostly adding new stuff (as we see safe tags or attributes is introduced). And this also means maintenance of this spec and implementation doesn't need to be rushed.

That's said, I think we can expose `CustomSanitizer`, which will allow developers to set whatever config they want, but we won't guarantee the safeness as well as won't integrate it with Trusted Types. That seems like a more reasonable way of dealing with custom tags/attributes to me.

CC: @mozfreddyb

**Comment by mozfreddyb** [comment]
I think we need to accept that this requires ongoing maintenance. For any point in time, we can assert which elements are supported by the browser and use those. And then, move incrementally.
