### ISSUE TITLE
Bypass via `SVGAnimationElement.onend`.

### ISSUE THREAD

**Issue by mikewest** [WICG/sanitizer-api#85]
A friendly, clever person notes that the `SVGAnimationElement.onend` attribute can be allowed via `allowElements`/`allowAttributes`, for example:

```js
<div id=div></div>
<script>
div.replaceChildren(
new Sanitizer({
    "allowElements":["svg","set"],
    "allowAttributes":{
        "onend": ["set"],
        "dur":["set"]
    }
}).sanitize(`<svg><set onend="alert(1)" dur="1"/></svg>`));
</script>
```

It's not clear to me whether this is supposed to be allowed per spec (perhaps related to https://github.com/WICG/sanitizer-api/issues/72?), so this might just be a Chromium issue.

**Comment by mozfreddyb** [comment]
Thank you for filing this!
As of right now, Firefox still doesn't allow the Sanitizer to be configured. So we are either not or not yet affected ;-)
However, I think we don't have that attribute on any internal allow-list, which ought to be checked while parsing options. So, I'm not sure how that would be let through :thinking:

**Comment by koto** [comment]
Wasn't the intention not to let trough any attribute which name starts with `on`? IIRC, there's nowhere a complete (and aligned with implementations) list of legitimate event handler attribute lists Sanitizer could refer to when validating the config.

**Comment by mozfreddyb** [comment]
My intention was to not let any attribute through if it isn't specifically marked as safe in the spec. Sure, you can supply something in the API but I thought we'd not include it in the _effective_ Sanitizer configuration if it isn't known to be safe. Regardless of whether it's an event handler or not.

**Comment by koto** [comment]
I'm confused :) So the expectation is that despite setting `onend` in `allowAttributes`, it's simply ignored because the internal (specced) allowlist doesn't include `onend`? That sounds fine as an approach (though you probably want to throw on sanitizer creation instead of silently dropping nodes that the clients will expect in the output)

But still there's this bypass - is it just an implementation bug?

**Comment by mozfreddyb** [comment]
EIther @otherdaniel and I need to sync up on how we understand the spec to work or we agree and then this is an implementation bug in Chrome. Firefox does not allow the `onend` attribute behavior, but we also don't implement the spec as it is currently written (e.g., we throw away whatever argument you pass to the constructor and still deal with the baked-in defaults).

As an aside, I don't think the call for testing was well timed. Certainly not for Firefox.

**Comment by otherdaniel** [comment]
Thank you for the report, friendly and clever person.

-----

What the spec (currently?) says:

- The spec currently pretends namespaces don't exist, so that config would allow the corresponding attributes/elements. That's a known omission, since we haven't yet agreed how or whether to handle these.
- The spec distiguishes between baseline and default. Neither allows `onend=`. But, the baseline is non-overridable, but only for 'known' elements and attributes. (§2.4.2, follow links to 'regular' for both element and attributes.) `onend=` is `unknown` (rather than `regular`. The reason is that otherwise it'd be impossible to ever handle anything not explicitly mentioned in the spec, at the time the spec was written, which struck me as excessive (and still does). 

With those two things, `onend=` is default-blocked but allow-able. The given sample config allows it.

IMHO, the "real" problem is that the spec presently ignores SVG - it neither handles nor (expressedly) forbids SVG, which makes this valid. And the problem would disappear if we'd agree on how to handle SVG (& MathML), pretty much regardless of which exact path we agree on.


> Wasn't the intention not to let trough any attribute which name starts with on? 

No, the intention was to block any attributes that the browser will execute as script. `one=` would not count, for example.


---- 

Chrome/Chromium: We presently implement this in a naive fashion, meaning any SVG content is allow-able, and hence this issue arrises. My present plan is to just block SVG (&MathML) non-overridably in the Chromium implementation until we have a properly specced solution, and then adopt whatever that'll be.
